name: KarmicShare

main: com.mitsugaru.KarmicShare.KarmicShare

version: 0.16

website: http://dev.bukkit.org/server-mods/karmicshare/

description: Community/Group item sharing with limiting karma system

authors:
  - Mitsugaru

softdepend: [Vault, PermissionsEX, Spout]

commands:
  ks:
    description: Root command for KarmicShare
    usage: /ks ? - Show help on KarmicShare

permissions:
    KarmicShare.*:
        description: Gives access to all KarmicShare commands
        children:
            KarmicShare.karma: true
            KarmicShare.give: true
            KarmicShare.take: true
            KarmicShare.admin: true
            KarmicShare.info: true
            KarmicShare.sign: true
            KarmicShare.chest: true
            KarmicShare.karma.other: true
            KarmicShare.commands.give: true
            KarmicShare.commands.take: true
        default: op
    KarmicShare.karma:
        description: Allows user view their karma
        default: op
    KarmicShare.karma.other:
        description: Allows user view another user's karma
        default: op
    KarmicShare.give:
        description: Allows user to give items to pool
        default: op
    KarmicShare.take:
        description: Allows user to take items from pool
        default: op
    KarmicShare.info:
        description: Allows user to inspect items
        default: op
    KarmicShare.chest:
        description: Allows user to use the chests
        default: op
    KarmicShare.sign:
        description: Allows user to make/destroy associated signs for chests
        default: op
    KarmicShare.ignore.karma:
        description: Ignores karma. User's karma does not change.
        default: false
    KarmicShare.ignore.group:
        description: Ignores groups. User is of all groups.
        default: false
    KarmicShare.ignore.*:
        description: Allows user to ignore all the things.
        default: false
        children:
            KarmicShare.ignore.karma: true
            KarmicShare.ignore.group: true
    KarmicShare.commands.give:
        description: Allows usage for command /ks give
        default: op
    KarmicShare.commands.take:
        description: Allows usage for command /ks take
        default: op
    KarmicShare.commands.*:
        description: Allows user to use all restricted commands
        default: op
        children:
            KarmicShare.ignore.karma: true
            KarmicShare.ignore.group: true
    KarmicShare.admin:
        description: Allows user to administrate plugin
        default: op
        children:
            KarmicShare.karma.other: true
            KarmicShare.info: true